dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: parctica7
  strategy: git
  api_key:
    secure: Zjd9CNCZibbS57nhe68C7vJEpZb6xkcE2dOL8yk6rdJyiPAnic5r1GGZrMvxVmaW305Gen5RISUSeiDO0+TINXZ7ahk+7fzuAW+1ZzXkrasMc/xxi+BRtlPSwkskrG1g5Dbqjo4eMjPZnSVMGcgFDljmzi8D1RH+MG3dGOohztbI11Aa94lurJxbM9tx46hRk0KmBMhwrnzF8n6/exkl0unOs6rP1hQFkmjspy+bBaN/XkqkeByfCWIhkLsvsFlCPSmCCq38U11J9sNsK8zMzAsU0Nstjm2tWaP0ETo+C/lZuyVsPrmR0k/sYlzx+GlE8cd+kzGz5YjQSRDfZIb5qF0Kk6w/8NUVLuZgxzh9DMogqUZ2NQ0c4AIVdvbAtQGXaH9tQPPAthFTm2SRA0s3fW2S9MAQAWQC+scl4KwI0HERfHaQBlQ5u3+jPn4XCDBvNYJaQYQV9z7E560HdOHj/vUEwSpAI+BwcExvGPvaKhXVMa1nXJmhbFF5A28xkSg8NTonX4RkMIlz4iy14ppEgGwItrsjbmeIc1L5L3WVgrmsVJ/pMbYYWQ6t7OxbtBwuPXJxXvP9ySiwToLgdPKMELdMzfYGsvnI1e5E8oMQVKMNDV6W5VbNcOTUFwBHMg0VjqSCeLzFY+2wARo2GNSySzFyFECA0xNuAWqXrCtpX9M=
